# =============================================================================
# CivicSense AI — Complaint Contracts
# =============================================================================
# Pydantic schemas for AI-generated complaint output.
# Owner: Arpit (Person 1)
# =============================================================================

from typing import Literal

from pydantic import BaseModel, Field

# Complaint priority aligns with severity levels
ComplaintPriority = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]


class ComplaintResult(BaseModel):
    """
    Structured complaint generated by the LLM from verified inputs.

    The complaint body is generated by the LLM, but authority contact
    information embedded in the complaint MUST come from verified
    AuthorityResult data, not from LLM generation.
    """

    subject: str = Field(..., description="Complaint subject line")
    body: str = Field(..., description="Full complaint body text")
    priority: ComplaintPriority = Field(..., description="Complaint priority level")
    requested_action: str | None = Field(
        default=None, description="Specific action requested from the authority"
    )
    generated_at: str = Field(
        ..., description="ISO timestamp of complaint generation"
    )
    source: str = Field(
        default="mock",
        description="Result source: 'mock' | 'ollama_llama3' | etc.",
    )
