# =============================================================================
# CivicSense AI — Mock Complaint Generator
# =============================================================================
# ⚠️  MOCK IMPLEMENTATION — NOT PRODUCTION CIVIC INTELLIGENCE
#
# This mock returns placeholder complaint text for development/testing.
# Will be replaced with real Ollama LLM generation in Phase 7.
#
# Owner: Arpit (Person 1)
# =============================================================================

_MOCK_WARNING = "⚠️ THIS IS A MOCK IMPLEMENTATION — NOT PRODUCTION CIVIC INTELLIGENCE"

from datetime import datetime, timezone

from app.core.interfaces import ComplaintGenerator
from app.contracts.complaint import ComplaintResult
from app.core.logging import get_logger

logger = get_logger(__name__)


class MockComplaintGenerator(ComplaintGenerator):
    """
    MOCK: Returns placeholder complaint text.

    Replace with real Ollama-based complaint generation in Phase 7.
    All outputs are clearly marked with source='mock'.
    """

    async def generate(self, decision_context: dict) -> ComplaintResult:
        logger.info("[MOCK] Complaint generation")

        issue_type = decision_context.get("issue_type", "civic issue")
        severity = decision_context.get("severity_level", "MEDIUM")
        address = decision_context.get("address", "Mock Address")
        authority = decision_context.get("authority_name", "Municipal Authority")
        department = decision_context.get("department", "Public Works")

        return ComplaintResult(
            subject=(
                f"[MOCK] {severity} Priority: {issue_type.replace('_', ' ').title()} "
                f"Reported at {address}"
            ),
            body=(
                f"[MOCK COMPLAINT — NOT PRODUCTION]\n\n"
                f"Dear {authority} — {department},\n\n"
                f"This is a mock complaint generated for development purposes.\n\n"
                f"Issue Type: {issue_type}\n"
                f"Severity: {severity}\n"
                f"Location: {address}\n\n"
                f"In a production system, this complaint would be generated by the "
                f"Ollama LLM using verified civic information from the RAG system "
                f"and authority data from the verified dataset.\n\n"
                f"This mock exists to validate the end-to-end pipeline structure.\n\n"
                f"Regards,\nCivicSense AI (Mock Mode)"
            ),
            priority=severity if severity in ("LOW", "MEDIUM", "HIGH", "CRITICAL") else "MEDIUM",
            requested_action=f"[MOCK] Inspect and repair the reported {issue_type}",
            generated_at=datetime.now(timezone.utc).isoformat(),
            source="mock",
        )
